Implement (dump) NATS reconnection attempts on startup
CyCoreSystems/ari-proxy pull request #38
Opened 2020-10-27 17:30 UTC by blaggacao

fixes #37

This is a non-configurable ("dump") implementation. I dind't think it was worth it to expose a configuration flag for all edge cases here. If the start up fails due to non connectivity after a total of 25 seconds, then a k8s restart loop probably is within the budget.

2020-10-27 17:32 UTC, blaggacao commented
```console
$ make ci
go mod verify
all modules verified
golangci-lint run
go build ./...
go build
go test ./...
?   	github.com/CyCoreSystems/ari-proxy/v5	[no test files]
ok  	github.com/CyCoreSystems/ari-proxy/v5/client	0.046s
ok  	github.com/CyCoreSystems/ari-proxy/v5/client/bus	0.012s
ok  	github.com/CyCoreSystems/ari-proxy/v5/client/cluster	0.056s
?   	github.com/CyCoreSystems/ari-proxy/v5/internal/integration	[no test files]
?   	github.com/CyCoreSystems/ari-proxy/v5/proxy	[no test files]
ok  	github.com/CyCoreSystems/ari-proxy/v5/server	0.058s
ok  	github.com/CyCoreSystems/ari-proxy/v5/server/dialog	0.005s
ok  	github.com/CyCoreSystems/ari-proxy/v5/session	0.002s
```

2020-11-11 17:42 UTC, Ulexus requested changes
nits and thanks!

Sorry I missed this PR.

2020-11-11 17:42 UTC, Ulexus commented on server/server.go
> +		time.Sleep(5 * time.Second)
magic numbers:  I'd prefer that this 5s value be made into a named package-scoped constant.

2020-11-11 17:42 UTC, Ulexus commented on server/server.go
> +	reconnectionAttempts := 5
magic numbers:  this should be a package-scoped named constant

2020-11-11 18:11 UTC, blaggacao commented
Fixed and force-pushed, please continue review / acceptance consideration.

2020-11-11 18:32 UTC, Ulexus approved these changes

2020-11-11 18:33 UTC, Ulexus commented
Thanks @blaggacao !

2020-11-11 18:33 UTC, merged